In [1]:
from numpy import e
import pandas as pd
import math


def CohenEffectSize(group1, group2):
    diff = group1.mean() - group2.mean()
    var1 = group1.var()
    var2 = group2.var()
    n1, n2 = len(group1), len(group2)
    pooled_var = (n1 * var1 + n2 * var2) / (n1 + n2)
    d = diff / math.sqrt(pooled_var)
    return d


one = {'a':23, 'b':34, 'c':56, 'd':767, 'e':789, 'f':00}
two = {'a':56, 'b':67, 'c':34, 'd':65, 'e':78, 'f':99}
ser_one = pd.Series(data=one, index=['a','b','c','d','e','f'])
ser_two = pd.Series(data=two, index=['a','b','c','d','e','f'])

print(CohenEffectSize(ser_one,ser_two)) 

0.7709834401901616


In [2]:
from scipy.stats import bernoulli

In [6]:
bernoulli.rvs(p=0.5, size=1)

array([0])

In [7]:
bernoulli.rvs(p=0.5, size=10)

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 1])

In [8]:
#how many heads
sum(bernoulli.rvs(p=.5, size=10))

5

In [9]:
import numpy as np
from scipy import stats

In [10]:
import numpy as np
from scipy import stats
n = 10
p = 0.3 
k = np.arrange(0,11)
binomial = stats.binom.pmf(k,n,p) 

AttributeError: module 'numpy' has no attribute 'arrange'

In [11]:
n = 10
p = 0.3
k = np.arange(0,11)
binomial = stats.binom.pmf(k,n,p)

In [12]:
binomial


array([2.82475249e-02, 1.21060821e-01, 2.33474441e-01, 2.66827932e-01,
       2.00120949e-01, 1.02919345e-01, 3.67569090e-02, 9.00169200e-03,
       1.44670050e-03, 1.37781000e-04, 5.90490000e-06])